language: python
python:
- '3.6'
os:
- linux
script:
- pip3 install -r requirements-dev.txt
- pip3 install coverage codacy-coverage
- pip3 install .
- python3 setup.py test
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: WntbiwLM21haCmm3hxEb3FY7H00OnWY/yDkmcd8e9SfGAhLBc4QNqw3q9/BgQxpx5c+Z7LCQRoMZso5RBZ9YgYsX91f9UspjNBYLGGWUmUMiabcxvKyENCJCw61RvxOinKy1Df1EcBmuSbLu6PfqzBy2XhVoIrZjWfpAzOikEJIxpEvoO91gY+r4f1CR5DnpkMutnVzEaiBoeM/Lc64AL7GMVzT3hzgiasVkaX7/lypTZw8UMkS//TucGnsMw82I0HBDbuMagSpQ/9TJ8Lcam7ocCxLO8JTkUE8f3bwPevPDoiFRIQmftcrucL88V6LCEUuhVzXKsdvLTtZJOqXKIlMvLEPNce2RBhFYTFzJ7yCwcbEiXpveQX3QWRb3v9GaQjOSCIHKsZDRlMhs0OT16mVsRwkny5zlhOkOwfiN+VJTwSkfKuICnDlGwkFfryeXqGlr2QieRI5RK5qMZJ3VjxcDjVxi8aJW5hvxGmtpJKGLRnejfuD6Prgz+e31kyrwp39nKlRAu8EtOWtYQgNfcgAfPX6Ijcju71aF9k2bRYghE/ZU6MnkqeRq4FoBEyNhbPbBypBVYWmTkWtMZZVue7m1i8w6zAPwHTNUX5HZpus0/vttaYFU0qsjvvWPz9bDIleFdhNxD5d3RLYHVzcbj3VTZtx942ipGOUN2xLj/lI=
